### PR TITLE
Reformat

### PR DESCRIPTION
**Pull request by willthames**
Move configuration out of playbook
Restructure roles to be more consistent with themselves.
Simplify and make more Ansible-ish in places (commit logs have more details)

### CODE REVIEW

**Comment by willthames** [comment]
Also, please note, I don't have an environment to test this, so apologies in advance if I've made any silly mistakes.

**Comment by willthames** [comment]
Note that k8s_remove has not been touched - I can apply the same to that if you like.

Also, there is scope for making create_context.yml converge (so that it returns `changed: False` on a second run. I'm not sure how best to approach that due to limited k8s knowledge, but here's something I prepared earlier: http://willthames.github.io/2016/09/21/using-command-and-shell-in-ansible.html

**Comment by sebgoa** [comment]
I am merging first and testing after :)

**Comment by sebgoa** [comment]
ok tested...it all works :) thanks a bunch

**Pull request merged**
